set background=dark
highlight Comment ctermfg=blue

set mouse=a

filetype plugin indent on     " required!

autocmd BufNewFile,BufRead *.md setlocal spell spelllang=en_us
set mousemodel=popup
set spellfile=~/spellfile.add

set nocompatible               " be iMproved
filetype off                   " required!

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" Vundle manages vundle
Bundle 'gmarik/vundle'

Bundle 'https://github.com/Valloric/YouCompleteMe.git'
Bundle 'https://github.com/scrooloose/nerdtree.git'

" Color schemes
Bundle 'altercation/vim-colors-solarized'
Bundle 'sickill/vim-monokai'

colorscheme molokai

" GUI-specific
if has("gui_running")
  set guifont=Inconsolata\ 13
  set formatoptions+=l
  set lbr
endif
